### ISSUE TITLE
A question about data_dir

### ISSUE THREAD

**Issue by disco14** [ayanc/fdscs#3]
When I execute the following code: 
                    ./run.py wts/bn600k.npz data_dir

I found i don't have this directory of data_dir. Also don't have *_10.png. Should I create such a directory by myself and download the relevant data? Can you give me some tips and help? 

By the way, your network is perfect.

**Comment by ayanc** [comment]
Please see the documentation on the structure of the data_dir. The *_10.png filenames match the convention of the KITTI training and test sets.
