### ISSUE TITLE
Train from scratch

### ISSUE THREAD

**Issue by fshamsafar** [ayanc/fdscs#6]
Hi,

I have modified the traditional cost computation part, and now I wish to start training on SceneFlow from beginning. What should I do in this regard? I noticed that in the codes, it only fine-tunes on the model trained already with 600K iterations.

Also could you put some comments on what the main difference is between these .py files {data.py, pdata.py and pproc.py}? And also these ones {train.py and ptrain.py}?

Thanks in advance.

**Comment by ayanc** [comment]
The code is setup to pre-train on the SceneFlow dataset and then finetune on KITTI. `ptrain.py` is the training script  for SceneFlow, and `train.py` is the training script for KITTI. These scripts use `pdata.py` and `data.py` files respectively for data loading—they are different in that they are setup to handle the SceneFlow and KITTI datasets respectively.

pproc.py is the data loading function for runtime. You will see it is used by run.py.
