### ISSUE TITLE
InvalidArgumentError

### ISSUE THREAD

**Issue by nickle-fang** [ayanc/fdscs#8]
Hello! When I run
 `./run.py wts/bn600k.npz data_dir`
I met the following error:

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
>     return fn(*args)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1317, in _run_fn
>     self._extend_graph()
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1352, in _extend_graph
>     tf_session.ExtendSession(self._session)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'Census' with these attrs.  Registered devices: [CPU,XLA_CPU], Registered kernels:
>   device='GPU'
> 
> 	 [[{{node Census}} = Census[](Tensordot)]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "./run.py", line 30, in <module>
>     sess.run(tf.global_variables_initializer())
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 929, in run
>     run_metadata_ptr)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
>     run_metadata)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'Census' with these attrs.  Registered devices: [CPU,XLA_CPU], Registered kernels:
>   device='GPU'
> 
> 	 [[node Census (defined at <string>:41)  = Census[](Tensordot)]]
> 
> Caused by op 'Census', defined at:
>   File "./run.py", line 28, in <module>
>     model = pp.Net()
>   File "/home/nickle/Desktop/fdscs/pproc.py", line 54, in __init__
>     self.graph()
>   File "/home/nickle/Desktop/fdscs/pproc.py", line 39, in graph
>     cv,lrl = lowrescv(limg,rimg)
>   File "/home/nickle/Desktop/fdscs/pproc.py", line 22, in lowrescv
>     limg, rimg = slib.census(limg), slib.census(rimg)
>   File "<string>", line 41, in census
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
>     op_def=op_def)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
>     op_def=op_def)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
>     self._traceback = tf_stack.extract_stack()
> 
> InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'Census' with these attrs.  Registered devices: [CPU,XLA_CPU], Registered kernels:
>   device='GPU'
> 
> 	 [[node Census (defined at <string>:41)  = Census[](Tensordot)]]
> 

And this is the environment I used:
Ubuntu 18.04
tensorflow==1.12.3
tensorflow-gpu==1.12.3
CUDA==10.2
I guess the problem is due to the tensorflow version. Because when I use tensorflow==1.14.0 or newer version, the `slib.so` can not be built. There are many `.h` fiels lost.
Could you please help?

**Comment by ayanc** [comment]
From reading the error messages, it looks like you do not have a GPU on the machine you are trying this on (only CPU devices are registered). The functions in slib require a GPU, even at test time.

**Comment by nickle-fang** [comment]
Thanks for help! But I do have a GPU on my machine. It seems that because I have `tensorflow` and `tensorflow-gpu`  packages simultaneously, the command `make.sh` just compile the lib using package `tensorflow`. So it didn't register the GPU.
But when I uninstall the `tensorflow` and just keep the `tensorflow-gpu`, it runs into a `no such file` error. So I wonder if it is the tensorflow version that cause the problem.

**Comment by nickle-fang** [comment]
Also, I downgrade the CUDA version to 10.1, the problem still exist.

**Comment by ayanc** [comment]
The original error message you posted suggests that:
- In your first try, the library WAS **compiled** with GPU support, because it says `Registered Kernels: [GPU]`
- But the version of tensorflow you were **executing** does not seem to recognize the GPU, because it says `Registered Devices: [CPU, XLA_CPU]` (*i.e., no GPU*). 

I don't quite understand what you mean by a no such file error. My best guess is this is a problem with your environment.

The code was originally written and tested in an older version of tensorflow (1.7). But it looks like people have been able to get it to work on more recent versions by modifying a bit of the code (see https://github.com/ayanc/fdscs/issues/2).

**Comment by ayanc** [comment]
Also, you can try the following modifications (based on #2 ) to the code to see if you can get it to compile for tensorflow 1.14 or 1.15.

1. In make.sh, change `nvcc -std=c++11 ...` to `nvcc -DNDEBUG -std=c++11 ...`
2. In the slib.cu.cc file, change `cuda_kernel_helper.h` in the last #include to `gpu_kernel_helper.h`
3. While being inside the slib directory, run the following commands:
```
mkdir -p third_party/gpus
ln -s /usr/local/cuda-10.x third_party/gpus/cuda
```
Here replace 10.x with your cuda verison (make sure this cuda version is compatible with the version of tensorflow-gpu you are using).

4. Then, run make.sh

**Comment by nickle-fang** [comment]
Thanks very much! 
After trying the command you list, I successfully compiled the `slib` library. However, there are still some problems. Sorry to bother you again.
With tensorflow-gpu==1.15.0 or later, the slib.so is successfully built. But the `import slib` python command meets a problem:
 
> Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import slib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libtensorflow_framework.so.1: cannot open shared object file: No such file or directory


And I can't find the file "libtensorflow_framework.so.1" in the tensorflow lib folder.

With tensorflow-gpu==1.14.0, the slib.so is successfully built. And I can find the "libtensorflow_framework.so.1" in the tensorflow lib folder, but "import slib" python command meets the same problem as before. And the command `./run.py wts/bn600k.npz data_dir` meets the following problem:

> /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint8 = np.dtype([("qint8", np.int8, 1)])
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint16 = np.dtype([("qint16", np.int16, 1)])
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint32 = np.dtype([("qint32", np.int32, 1)])
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   np_resource = np.dtype([("resource", np.ubyte, 1)])
> /usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint8 = np.dtype([("qint8", np.int8, 1)])
> /usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
> /usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint16 = np.dtype([("qint16", np.int16, 1)])
> /usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
> /usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint32 = np.dtype([("qint32", np.int32, 1)])
> /usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   np_resource = np.dtype([("resource", np.ubyte, 1)])
> WARNING:tensorflow:From /home/nickle/Desktop/fdscs/pproc.py:32: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.
> 
> WARNING:tensorflow:From /home/nickle/Desktop/fdscs/pproc.py:36: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use `tf.cast` instead.
> WARNING:tensorflow:From /home/nickle/Desktop/fdscs/pproc.py:12: The name tf.mod is deprecated. Please use tf.math.mod instead.
> 
> WARNING:tensorflow:From /home/nickle/Desktop/fdscs/pproc.py:15: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.
> 
> Segmentation fault (core dumped)

When I try to install tensorflow-gpu==1.7.0 as you mentioned, I found that this version needs CUDA 8.0 and Ubuntu 16.04. But I am using 18.04.
The problem might be caused by the tensorflow environment error. I will be very appreciated if you could help. And I am very interested in your paper.
Thanks again!

**Comment by ayanc** [comment]
- For Tensorflow 1.15: If you google the tensorflow framework error, you'll find that people have reported that the file is available as ..framework.so instead of ...framework.so.1 (and can be fixed by copying that to the name .so.1).
- For Tensorflow 1.14: What do you mean you mean "import slib meets the same error as before" ? Looking at your output, the only error I see is the segmentation fault. Everything else seems to be warnings.
- Tensorflow 1.7.0 does need cuda-8.0, but the Ubuntu 18.04 should not be a problem.

I don't know why you are getting a segmentation fault error with tensorflow 1.14. I just compiled slib (with the above modifications) on tensorflow 1.14 and was able to run the code without any problems.

This might be a problem with your environment or how you are setting up the data directory. Have you put the right data in the data_dir (i.e., corresponding color images named *_10.png from the KITTI dataset in left/ and right/ sub-folders) ?

**Comment by nickle-fang** [comment]
Sorry to bother you again, the segmentation fault error still exists.
I added some outputs to the code and found that the error is from
`model = pp.Net()` in `run.py` => 
`cv,lrl = lowrescv(limg,rimg)` in `pproc.py` => 
`limg, rimg = slib.census(limg), slib.census(rimg)` in `pproc.py`. 
So when it runs to line `limg, rimg = slib.census(limg), slib.census(rimg)` in `pproc.py` it meets a segmentation fault error. It happens before loading model and picture files.

**Comment by nickle-fang** [comment]
Here is the file tree:

> ├── data
│   ├── ftrain.txt
│   ├── fval.txt
│   ├── train.txt
│   └── val.txt
├── data_dir
│   ├── est
│   ├── left
│   │   └── 000000_10.png
│   └── right
│       └── 000000_10.png
├── data.py
├── dops.py
├── instats.py
├── model.py
├── pdata.py
├── popstats.py
├── pproc.py
├── ptrain.py
├── __pycache__
│   ├── model.cpython-36.pyc
│   ├── pproc.cpython-36.pyc
│   └── utils.cpython-36.pyc
├── README.md
├── run.py
├── slib
│   ├── __init__.py
│   ├── make.sh
│   ├── __pycache__
│   │   └── __init__.cpython-36.pyc
│   ├── slib.cc
│   ├── slib.cu.cc
│   ├── slib.so
│   └── third_party
│       └── gpus
│           └── cuda -> /usr/local/cuda-10.0
├── train.py
├── utils.py
└── wts
    ├── bn600k.npz
    ├── model_350000.npz
    └── model_600000.npz

12 directories, 30 files

**Comment by nickle-fang** [comment]
Here is the file tree:
![image](https://user-images.githubusercontent.com/45991928/95052906-443c0a00-0722-11eb-8e53-ca6b6e0149fe.png)

And I try to run python 3.6 in terminal under directory /fdscs:
It seems that the `slib` is successfully imported.
_>>> slib.census
<function census at 0x7f7e0c02cbf8>_
_>>> slib.hamming
<function hamming at 0x7f7e0c02cea0>_

**Comment by ayanc** [comment]
I'm not  sure what's going on at this point. As I said, I've tested this on Tensorflow 1.14 with the above changes, and it runs without any problems. Others seem to have also been able to run it on Tensorflow 1.15. 

If the error happens in the call to slib in pproc.py, this means it is happening during graph construction before any actual computation, so during kernel registration and before the actual code inside census or hamming Compute functions (in slib.cc) is being called.

The errors you have been getting with the different Tensorflow versions are a bit unusual. In your original message, there was no error in the census call during graph construction in Tensorflow 1.12 and no segmentation fault, and so it is strange that you're getting an error with this now for 1.14. Also, the code in 1.12 version should have worked if you have a GPU ... the error messages indicated it was compiled properly with the GPU kernels, but the problem was that it was not being called with GPU support.

My best guess is that there is a problem with your environment---because you have multiple versions of tensorflow and cuda installed, it may be linking / compiling the library with one version and running it with another.
