### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'Census' used by node Census (defined at /home/sgl/anaconda3/envs/stereo/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) 

### ISSUE THREAD

**Issue by sglshanghai** [ayanc/fdscs#9]
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'Census' used by node Census (defined at /home/sgl/anaconda3/envs/stereo/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) with these attrs: []
Registered devices: [CPU, XLA_CPU, XLA_GPU]
Registered kernels:
  device='GPU'

请问一下这个问题怎么能解决

**Comment by ayanc** [comment]
This may not work in recent versions of tensorflow that use xla.
